services:
  grafana:
    build:
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-12.3.0}
        development: true
        anonymous_auth_enabled: true
    ports:
      - 3000:3000/tcp
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
